apiVersion: v1
kind: Pod
metadata:
  name: app2
  namespace: default
  labels:
    app: app2
spec:
  containers:
  - name: app2
    image: "nginx:latest"
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: default
spec:
  selector:
    app: app2
  type: ClusterIP
  ports:
  - name: app2
    protocol: TCP
    port: 80
    targetPort: 80