apiVersion: v1
kind: Pod
metadata:
  name: app3
  namespace: default
  labels:
    app: app3
spec:
  containers:
  - name: app3
    image: "nginx:latest"
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: app3-service
  namespace: default
spec:
  selector:
    app: app3
  type: ClusterIP
  ports:
  - name: app3
    protocol: TCP
    port: 80
    targetPort: 80