# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bullseye64"

	config.vm.define "eassouliS" do |control|
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.hostname = "eassouliS"
		config.vm.provision "file", source: "./confs", destination: "$HOME/"
		control.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install curl -y
			curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=eth1 --token 12345" sh -s -
			sudo k3s kubectl apply -f confs/services/app1-service.yaml -f confs/services/app2-service.yaml -f confs/services/app3-service.yaml
			sudo k3s kubectl apply -f confs/deployments/app1-deployment.yaml -f confs/deployments/app2-deployment.yaml -f confs/deployments/app3-deployment.yaml
			sudo k3s kubectl apply -f confs/ingress/ingress.yaml
		SHELL
		control.vm.provider "virtualbox" do |vb|
			vb.name = "eassouliS"
			vb.memory = "1024"
			vb.cpus = 1
		end
	end
end
