apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: default
spec:
  selector:
    app: app1
  type: ClusterIP
  ports:
  - name: app1
    protocol: TCP
    port: 80
    targetPort: 80