apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: default
spec:
  selector:
    app: app2
  type: ClusterIP
  ports:
  - name: app2
    protocol: TCP
    port: 80
    targetPort: 80