apiVersion: v1
kind: Service
metadata:
  name: app3-service
  namespace: default
spec:
  selector:
    app: app3
  type: ClusterIP
  ports:
  - name: app3
    protocol: TCP
    port: 80
    targetPort: 80