# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bullseye64"
  # config.vm.box_check_update = false

	config.vm.define "eassouliS" do |control|
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.hostname = "eassouliS"
		control.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install curl -y
			curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=eth1 --token 12345" sh -s -
		SHELL
		control.vm.provider "virtualbox" do |vb|
			vb.name = "eassouliS"
			vb.memory = "1024"
			vb.cpus = 1
		end
	end
	config.vm.define "eassouliSW" do |agent|
		agent.vm.network "private_network", ip: "192.168.56.111"
		agent.vm.hostname = "eassouliSW"
		agent.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install curl -y
			curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 --flannel-iface=eth1" K3S_TOKEN=12345 sh -s -
		SHELL
		agent.vm.provider "virtualbox" do |vb|
			vb.name = "eassouliSW"
			vb.memory = "1024"
			vb.cpus = 1
		end
	end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
