# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.box_check_update = true

	config.vm.define "eassouliS" do |control|
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.hostname = "eassouliS"
		control.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install curl -y
			curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=eth1 --token 12345" sh -s
		SHELL
		control.vm.provider "virtualbox" do |vb|
			vb.name = "eassouliS"
			vb.memory = "1024"
			vb.cpus = 1
		end
	end
	config.vm.define "eassouliSW" do |agent|
		agent.vm.network "private_network", ip: "192.168.56.111"
		agent.vm.hostname = "eassouliSW"
		agent.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install curl -y
			curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 --flannel-iface=eth1" K3S_TOKEN=12345 sh -s
		SHELL
		agent.vm.provider "virtualbox" do |vb|
			vb.name = "eassouliSW"
			vb.memory = "1024"
			vb.cpus = 1
		end
	end
end
