# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.box_check_update = true

	config.vm.define "eassouliS" do |control|
		control.vm.network "private_network", ip: "192.168.56.112"
		control.vm.hostname = "eassouliS"
		config.vm.provision "file", source: ".", destination: "$HOME/"
		config.vm.provision "file", source: "../bonus", destination: "$HOME/"
		control.vm.provider "virtualbox" do |vb|
			vb.name = "eassouliS"
			vb.memory = "8196"
			vb.cpus = 6
		end
	end
end
